services:
  api:
    build: .
    environment:
      PORT: 3000
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/recetario
      JWT_SECRET: dev-secret
      CORS_ORIGINS: http://localhost:5173,http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo_data:
